name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest-16-cores
    env:
      GRADLE_ARGS: --stacktrace
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: |
            8
            16
            17
            21

      - name: Build
        run: ./gradlew build ${{ env.GRADLE_ARGS }}

      - name: Generate checksums
        run: sha256sum versions/*/build/libs/* loader/{container,stage{0,1,2}}/{fabric,launchwrapper,modlauncher{8,9}}/build/libs/* | tee checksums.txt

      - uses: actions/upload-artifact@v4
        with:
          name: checksums
          path: checksums.txt

      # Upload the raw jars to aid in debugging non-determinism issues if we got a checksum mismatch
      - uses: actions/upload-artifact@v4
        if: ${{ failure() && steps.verify.conclusion == 'failure' }}
        with:
          name: mod-jars
          path: versions/*/build*
          # These are fairly large, so we do not want to keep them around for particularly long.
          # Once fully deployed, one can simply fetch the jar from Essential infrastructure instead.
          retention-days: 1
